[[constraint]]
  name = "github.com/akamai/AkamaiOPEN-edgegrid-golang"
  version = "0.7.2"

[[constraint]]
  branch = "master"
  name = "github.com/akamai/cli-common-golang"

[[constraint]]
  branch = "master"
  name = "github.com/dshafik/gozone"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.6.0"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
